---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Data lists
- type: document
  path: data/about.yml
  label: About list
- type: document
  path: data/client.yml
  label: Client list
- type: document
  path: data/contact.yml
  label: Contact list
- type: document
  path: data/feature.yml
  label: Feature list
- type: document
  path: data/gallery.yml
  label: Gallery list
- type: document
  path: data/service.yml
  label: Service list
- type: document
  path: data/team.yml
  label: Team list
- type: heading
  label: Content
- type: document
  path: content/about/info.md
  label: Info Page
- type: directory
  path: content/blog-posts
  label: Blog posts
  create: all
  match: "**/*"
  templates:
  - blog
- type: directory
  path: content/portfolio
  label: Portfolio
  create: all
  match: "**/*"
  templates:
  - portfolio-item
- type: directory
  path: content/service
  label: Service
  create: all
  match: "**/*"
- type: document
  path: content/data/authors.yaml
  label: Authors List
- type: heading
  label: Config
- type: document
  path: themes/tale-theme/data/Settings.toml
  label: Design Settings
- type: document
  path: config.toml
  label: Site Config
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.61.0
  preview_output_directory: public
  install_dependencies_command: ' git submodule add https://github.com/themefisher/timer-hugo.git
    themes/timer echo ''theme = "timer"'' >> config.toml'
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
